name: release
on: workflow_dispatch

jobs:
  release:
    name: Build native gems
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby-platform:
        - x86_64-linux
        - aarch64-linux
        - x86_64-darwin
        - arm64-darwin
    steps:
    - uses: actions/checkout@v3

    - uses: oxidize-rb/actions/setup-ruby-and-rust@v1
      with:
        ruby-version: "3.2"

    - uses: oxidize-rb/cross-gem-action@main
      with:
        platform: ${{ matrix.ruby-platform }}
        ruby-versions: "3.0, 3.1, 3.2"
